### ISSUE TITLE
Set up SEO tools

### ISSUE THREAD

**Issue by lukefretwell** [ATO-ASAP/website#5]
@openprivacy I'm trying to set up the SEO tools for this but am getting this message.

Is this something you can handle?

```
Instructions for:
1. Sign in to your domain name provider (e.g. godaddy.com or namecheap.com)
2. Copy the TXT record below into the DNS configuration for atoasap.org
google-site-verification=VXufbxbDBzr-GOgcwRHclT9VtSHRyvQ4qJ6j350fbW4
3. Press verify below
Note: DNS changes may take some time to apply. If Search Console doesn’t find the record immediately, wait a day and then try to verify again
```

**Comment by openprivacy** [comment]
Added the TXT record - it should show up in about 10 minutes - will check in the morning.

**Comment by openprivacy** [comment]
Done:
```
» drill txt atoasap.org | grep TXT
;; atoasap.org.	IN	TXT
atoasap.org.	1757	IN	TXT	"v=spf1 include:spf.efwd.registrar-servers.com ~all"
atoasap.org.	1757	IN	TXT	"google-site-verification=VXufbxbDBzr-GOgcwRHclT9VtSHRyvQ4qJ6j350fbW4"
```

**Comment by lukefretwell** [comment]
@openprivacy it's still not verifying. Thoughts?

https://search.google.com/u/3/search-console/welcome?utm_source=about-page

**Comment by openprivacy** [comment]
@lukefretwell Was not verified - thanks for the link above - I have verified and it now says I am a verified owner. Hope this means you are, too.

**Update:** added you as a full user
